apiVersion: v1
kind: Secret
metadata:
  name: my-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-cert>
  tls.key: <base64-encoded-key>


tls:
  enabled: true
  secretName: my-tls-secret

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: my-app
          image: my-image:latest
          volumeMounts:
            - name: tls-secret-volume
              mountPath: "/etc/tls"
              readOnly: true
      volumes:
        - name: tls-secret-volume
          secret:
            secretName: {{ .Values.tls.secretName }}

          env:
            - name: TLS_CERT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.tls.secretName }}
                  key: tls.crt
            - name: TLS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.tls.secretName }}
                  key: tls.key
