apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/values.yaml   # Inheriting base values
  - values-dev.yaml          # Overrides for dev environment
  - helmrelease-busybox.yaml # The HelmRelease




apiVersion: v1
kind: ConfigMap
metadata:
  name: busybox-values
  namespace: default
data:
  values.yaml: |
    command: ["sh", "-c", "echo 'ENVIRONMENT is set to: $ENVIRONMENT'; sleep 3600"]
    env:
      ENVIRONMENT: "base"






apiVersion: v1
kind: ConfigMap
metadata:
  name: busybox-values
  namespace: default
data:
  values.yaml: |
    command: ["sh", "-c", "echo 'ENVIRONMENT is set to: $ENVIRONMENT'; sleep 9999"]
    env:
      ENVIRONMENT: "dev"




apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: busybox
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: busybox
      sourceRef:
        kind: HelmRepository
        name: bitnami
  valuesFrom:
    - kind: ConfigMap
      name: busybox-values
      valuesKey: values.yaml
  values:
    image:
      repository: busybox
      tag: latest
    extraEnv:
      - name: ENVIRONMENT
        valueFrom:
          configMapKeyRef:
            name: busybox-values
            key: values.yaml
