name: Build & Push Docker Image with Managed Identity

on:
  workflow_dispatch:

env:
  REGISTRY: your-acr-name.azurecr.io
  IMAGE_NAME: flux-helpers

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure using Managed Identity
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }} # <-- This is your UAMI's client ID
          enable-managed-identity: true

      - name: Login to ACR
        run: |
          az acr login --name ${{ env.REGISTRY }}

      - name: Build and push Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:latest -f .github/flux-helper/Dockerfile .
          docker push $REGISTRY/$IMAGE_NAME:latest
