apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: my-app
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
        namespace: flux-system
  values:
    replicaCount: 2
    image:
      repository: nginx
      tag: 1.21.6
