apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-test-connection"
  labels:
    {{- include "your_chart_name.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ['sh', '-c', 'curl -s -o /dev/null -w "%{http_code}" http://{{ .Release.Name }}-service:80 | grep 200']
  restartPolicy: Never
