apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: helm-controller
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - --watch-all-namespaces=false
          - --no-cross-namespace-refs=true
