name: 'Close stale PRs'
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR has been automatically marked as stale due to inactivity. It will be closed in 7 days if no further activity occurs.'
          close-pr-message: 'This PR was automatically closed due to inactivity.'
          days-before-stale: 30
          days-before-close: 7
          stale-pr-label: 'stale'
          exempt-pr-labels: 'keep-open,wip,blocked'
