apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-test
  namespace: cluster-config
spec:
  interval: 1m0s
  chart:
    spec:
      chart: secrets-test   # Replace with your chart name
      version: "0.1.0"      # Chart version
      sourceRef:
        kind: GitRepository
        name: my-gitops-repo   # Your Git repository resource name
        namespace: flux-system # Typically flux-system
  values:
    image:
      repository: docker.io/library/busybox
      tag: "latest"
      pullPolicy: IfNotPresent
    pod:
      command: ["sh", "-c", "cat /mnt/secrets/testsecret && sleep 3600"]
      volumeMounts:
        - name: secrets-store-inline
          mountPath: /mnt/secrets
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store-csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kv"
