apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-workload-sa
  namespace: cluster-config
  annotations:
    azure.workload.identity/use-workload-identity: "true"
    azure.workload.identity/client-id: "<your-managed-identity-client-id>"
    azure.workload.identity/tenant-id: "<your-tenant-id>"
